package fit

const (
	FIT_MESG_NUM_FILE_ID     = 0
	FIT_MESG_SESSION         = 18
	FIT_MESG_LAP             = 19
	FIT_MESG_RECORD          = 20
	FIT_MESG_EVENT           = 21
	FIT_MESG_DEVICE_INFO     = 23
	FIT_MESG_ACTIVITY        = 34
	FIT_MESG_NUM_FIELD_DESC  = 206
	FIT_MESG_NUM_DEV_DATA_ID = 207
)
